export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const INIT_ALERT = 'INIT_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';


export const FETCH_LATEST_MOVIES= 'FETCH_LATEST_MOVIES';
export const ADD_LATEST_MOVIES = 'ADD_LATEST_MOVIES';
export const SET_LOADING = 'SET_LOADING';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIE_DATA = 'FETCH_MOVIE_DATA';
export const INSERT_MOVIE_DATA = 'INSERT_MOVIE_DATA';

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADDTO_FAVORITE_START = "ADDTO_FAVORITE_START";
export const ADDTO_FAVORITE_SUCCESS = "ADDTO_FAVORITE_SUCCESS";
export const ADDTO_FAVORITE_FAIL = "ADDTO_FAVORITE_FAIL";

export const ADDTO_WATCHLIST_START = "ADDTO_WATCHLIST_START";
export const ADDTO_WATCHLIST_SUCCESS = "ADDTO_WATCHLIST_SUCCESS";
export const ADDTO_WATCHLIST_FAIL = "ADDTO_WATCHLIST_FAIL";
export const AUTH_AUTOLOGIN = "AUTH_AUTOLOGIN";

export const FETCH_USER_REVIEW = "FETCH_USER_REVIEW";
export const ADDTO_REVIEW_START = "ADDTO_REVIEW_START";
export const ADDTO_REVIEW_SUCCESS = "ADDTO_REVIEW_SUCCESS";
export const ADDTO_REVIEW_FAIL = "ADDTO_REVIEW_FAIL";


export const FETCH_MYFAVORITE_START = "FETCH_MYFAVORITE_START";
export const FETCH_MYFAVORITE_SUCCESS = "FETCH_MYFAVORITE_SUCCESS";
export const FETCH_MYFAVORITE_FAIL = "FETCH_MYFAVORITE_FAIL";

export const FETCH_WATCHLIST_START = "FETCH_WATCHLIST_START";
export const FETCH_WATCHLIST_SUCCESS = "FETCH_WATCHLIST_SUCCESS";
export const FETCH_WATCHLIST_FAIL = "FETCH_WATCHLIST_FAIL";

export const REMOVE_FAV_START = "REMOVE_FAV_START";
export const REMOVE_FAV_SUCCESS = "REMOVE_FAV_SUCCESS";
export const REMOVE_FAV_FAIL = "REMOVE_FAV_FAIL";

export const REMOVE_WATCH_START = "REMOVE_WATCH_START";
export const REMOVE_WATCH_SUCCESS = "REMOVE_WATCH_SUCCESS";
export const REMOVE_WATCH_FAIL = "REMOVE_WATCH_FAIL";



export const removeUserOnLogout = ()=>
{
    localStorage.removeItem("token");
    localStorage.removeItem("expirationDate");
    localStorage.removeItem("userId");
}